/home/bp/VirtualEnvs/virtualenv_3.5.2/bin/python3.5 /home/bp/PycharmProjects/kg_quora_insincere_questions_classification/kg_quora_insincere_questions_classification/src/own_solutions/self_solution_2/entrance.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/bp/PycharmProjects/kg_quora_insincere_questions_classification/kg_quora_insincere_questions_classification/src/own_solutions/self_solution_2/entrance.py", line 119, in <module>
    model = train_tuple.build_fn(max_len, max_features, embedding_matrix)
  File "/home/bp/PycharmProjects/kg_quora_insincere_questions_classification/kg_quora_insincere_questions_classification/src/own_solutions/self_solution_2/model_utils.py", line 66, in build_fn
    inp)
  File "/home/bp/VirtualEnvs/virtualenv_3.5.2/lib/python3.5/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/bp/VirtualEnvs/virtualenv_3.5.2/lib/python3.5/site-packages/keras/layers/embeddings.py", line 106, in build
    dtype=self.dtype)
  File "/home/bp/VirtualEnvs/virtualenv_3.5.2/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/bp/VirtualEnvs/virtualenv_3.5.2/lib/python3.5/site-packages/keras/engine/base_layer.py", line 249, in add_weight
    weight = K.variable(initializer(shape),
  File "/home/bp/VirtualEnvs/virtualenv_3.5.2/lib/python3.5/site-packages/keras/initializers.py", line 112, in __call__
    dtype=dtype, seed=self.seed)
  File "/home/bp/VirtualEnvs/virtualenv_3.5.2/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 4049, in random_uniform
    dtype=dtype, seed=seed)
  File "/home/bp/VirtualEnvs/virtualenv_3.5.2/lib/python3.5/site-packages/tensorflow/python/ops/random_ops.py", line 235, in random_uniform
    shape = _ShapeTensor(shape)
  File "/home/bp/VirtualEnvs/virtualenv_3.5.2/lib/python3.5/site-packages/tensorflow/python/ops/random_ops.py", line 44, in _ShapeTensor
    return ops.convert_to_tensor(shape, dtype=dtype, name="shape")
  File "/home/bp/VirtualEnvs/virtualenv_3.5.2/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1050, in convert_to_tensor
    as_ref=False)
  File "/home/bp/VirtualEnvs/virtualenv_3.5.2/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/bp/VirtualEnvs/virtualenv_3.5.2/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/bp/VirtualEnvs/virtualenv_3.5.2/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/bp/VirtualEnvs/virtualenv_3.5.2/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 443, in make_tensor_proto
    nparray = np.array(values, dtype=np_dt)
ValueError: setting an array element with a sequence.